### ISSUE TITLE
Spacing Issue 

### ISSUE THREAD

**Issue by nadeemSabasoft** [jaroslavstehlik/svgimporter#10]
While Creating SVG Asset from the SVG file there's a weird kind of spacing between two layers just like shown in the below-attached screenshots. Is there any solution regarding this? I have attached these assets in zip.

<img width="1440" alt="Screenshot 2021-04-02 at 11 26 57 AM" src="https://user-images.githubusercontent.com/81796503/113388025-ddcd3700-93a6-11eb-84f9-9523b9e3a726.png">
<img width="1440" alt="Screenshot 2021-04-02 at 11 25 30 AM" src="https://user-images.githubusercontent.com/81796503/113388038-e45bae80-93a6-11eb-9b26-2359cc179ba7.png">
<img width="1440" alt="Screenshot 2021-04-02 at 11 25 16 AM" src="https://user-images.githubusercontent.com/81796503/113388040-e58cdb80-93a6-11eb-9af2-8b42c128ca4a.png">
[SVG Assets.zip](https://github.com/jaroslavstehlik/svgimporter/files/6248052/SVG.Assets.zip)

**Comment by jaroslavstehlik** [comment]
The tesselation is not perfect, because it is optimized "decreased number of vertices"
1. You can disable optimization on assets
2. You can inflate the shape on top to minimize the outlines or deflate the shape underneath.

**Comment by nadeemSabasoft** [comment]
Thank You for this wonderful asset Sir.
