### ISSUE TITLE
How to properly import into new project?

### ISSUE THREAD

**Issue by crossplatformdev** [jaroslavstehlik/svgimporter#9]
Hi,

I downloaded master branch, opened in Unity 2020, and exported packages, in order to import them back in the new project.

However, I got the following error:

"Cannot Load SVG Importer Settings! Please Move SVG Importer Settings in to Resource folder."

Where is Resource folder? What is the correct way to set up a project?

Thank you.

**Comment by ArtemStankevich** [comment]
Same. Any tips for solving this problem? I just moved the contents of the "Assets" folder into my empty test project and ran into the same error.

**Comment by XaeroDegreaz** [comment]
You can just create a `Resources` folder in your `Assets` directory, and then move the `svgImporterSettings.asset` that gets generated in the root of your `Assets` directory the first time you import the code. You may have to restart Unity to trigger reloading the asset.
